import mongoose from 'mongoose';


const projectLinkSchema = new mongoose.Schema(
  {
    label: { type: String, required: true, trim: true },
    url: { type: String, required: true, trim: true },
    type: { type: String, trim: true, default: 'other' },   // ← free string
  },
  { _id: true }
);

// ---------- client installment ----------
const clientPaymentSchema = new mongoose.Schema(
  {
    amount: { type: Number, required: true, min: 1 },
    method: {
      type: String,
      enum: ['bank_transfer', 'upi', 'cash', 'cheque', 'other'],
      default: 'other',
    },
    reference: { type: String, trim: true },       // NEFT ID / UPI ref / cheque no.
    note: { type: String, trim: true },
    receivedAt: { type: Date, default: Date.now }, // when client actually paid

    // commission generated by this installment
    commissionPaid: { type: Boolean, default: false },
    commissionAmount: { type: Number, default: 0 },
  },
  { _id: true, timestamps: true }
);

// ---------- commission payout to partner ----------
const commissionPaymentSchema = new mongoose.Schema(
  {
    amount: { type: Number, required: true, min: 1 },
    clientPaymentId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,   // link to the installment that triggered this
    },
    note: { type: String, trim: true },
    paidAt: { type: Date, default: Date.now },
  },
  { _id: true, timestamps: true }
);

const projectSchema = new mongoose.Schema(
  {
    // ---------- links ----------
    lead: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Lead',
      required: true,
    },
    partner: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },

    // ---------- client snapshot ----------
    clientName: { type: String, required: true, trim: true },
    clientEmail: { type: String, trim: true, lowercase: true },
    clientNumber: { type: String, required: true, trim: true },
    clientAddress: { type: String, trim: true },

    // ---------- project details ----------
    projectName: { type: String, trim: true },
    projectType: {
      type: String,
      enum: ['app', 'website', 'digital_marketing'],
    },
    reference: { type: String, trim: true },
    description: { type: String, trim: true },

    // ---------- budget ----------
    budget: { type: Number, default: 0 },
    totalPaid: { type: Number, default: 0 },     // derived from clientPayments
    balanceDue: { type: Number, default: 0 },    // budget - totalPaid

    // ---------- commission config ----------
    commissionRate: { type: Number, default: 0, min: 0, max: 100 },  // %
    totalCommission: { type: Number, default: 0 },                   // budget × rate / 100
    commissionCredited: { type: Number, default: 0 },                // sum so far
    commissionBalance: { type: Number, default: 0 },                 // total - credited

    // ---------- payment tracking ----------
    clientPayments: [clientPaymentSchema],          // installments from client
    commissionPayments: [commissionPaymentSchema],  // payouts to partner

    // ---------- timeline ----------
    timePeriod: { type: String, trim: true },
    startDate: { type: Date },
    expectedEndDate: { type: Date },

    // ---------- requirements ----------
    requirements: { type: String, trim: true },

    // ---------- status ----------
    projectStatus: {
      type: String,
      enum: ['not_started', 'in_progress', 'on_hold', 'completed', 'cancelled'],
      default: 'not_started',
    },

    projectLinks: [projectLinkSchema],

    // ---------- meta ----------
    convertedAt: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

const Project = mongoose.model('Project', projectSchema);

export default Project;